version: '3'

services:
  lcc1:
    build: ./lcc1
    ports:
      - "3101:3101"
    networks:
      - lcc-network

  lcc2:
    build: ./lcc2
    ports:
      - "3102:3102"
    networks:
      - lcc-network

  lcc3:
    build: ./lcc3
    ports:
      - "3103:3103"
    networks:
      - lcc-network

  client:
    build: ./client
    ports:
      - "80:80"
    networks:
      - lcc-network

networks:
  lcc-network:
    driver: bridge
